name: CI Build & Analysis

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt-get install -y gcc-arm-none-eabi cppcheck clang-format
    - name: Check for Makefile
      run: |
        if [ ! -f Makefile ]; then
          echo "Error: Makefile not found!"
          exit 1
        fi
    - name: Build Project
      run: make clean && make all
    - name: Check for Source Files
      run: |
        if [ -d "Src" ]; then
          echo "Source directory found."
        else
          echo "Source directory not found! Exiting..."
          exit 1
        fi
        if [ -d "Inc" ]; then
          echo "Include directory found."
        else
          echo "Include directory not found! Exiting..."
          exit 1
        fi
    - name: Static Analysis
      run: cppcheck --enable=all --inconclusive Src/ Inc/
    - name: Code Formatting
      run: clang-format -i Src/*.c Inc/*.h
