name: SonarQube Static Analysis for STM32

on: [push, pull_request]

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi make

    - name: Install SonarQube Scanner
      run: |
        wget https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.6.2.2472/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner-cli-4.6.2.2472-linux.zip
        sudo mv sonar-scanner-4.6.2.2472-linux /usr/local/sonar-scanner

    - name: Run SonarQube Analysis
      run: |
        export SONAR_SCANNER_HOME=/usr/local/sonar-scanner
        export PATH=$SONAR_SCANNER_HOME/bin:$PATH
        sonar-scanner -Dsonar.projectKey=stm32-project -Dsonar.host.url=http://localhost:9000 -Dsonar.login=${{ secrets.SONAR_TOKEN }}
